# Generated by Django 2.2.4 on 2019-08-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190827_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='test1',
            name='LastContactMonth',
            field=models.CharField(default='', max_length=200),
        ),
    ]
