# Generated by Django 2.2.4 on 2019-08-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test1_lastcontactmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Age', models.IntegerField()),
                ('Job', models.CharField(default='', max_length=200)),
                ('Marital', models.CharField(default='', max_length=200)),
                ('Education', models.CharField(default='', max_length=200)),
                ('Default', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('HHInsurance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('CarLoan', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Communication', models.CharField(default='', max_length=200)),
                ('LastContactDay', models.DecimalField(decimal_places=10, max_digits=19)),
                ('LastContactMonth', models.CharField(default='', max_length=200)),
                ('NoOfContacts', models.DecimalField(decimal_places=10, max_digits=19)),
                ('DaysPassed', models.DecimalField(decimal_places=10, max_digits=19)),
                ('PrevAttempts', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Outcome', models.CharField(default='', max_length=200)),
                ('CallStart', models.CharField(default='', max_length=200)),
                ('CallEnd', models.CharField(default='', max_length=200)),
                ('CarInsurance', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
