# Generated by Django 2.2.4 on 2019-08-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190827_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
