# Generated by Django 2.2.4 on 2019-08-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_test2_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='featured',
        ),
    ]
